program PolySlerp1DxS3;

uses
  System.StartUpCopy,
  FMX.Forms,
  LUX in '_LIBRARY\LUXOPHIA\LUX\LUX.pas',
  LUX.D1 in '_LIBRARY\LUXOPHIA\LUX\LUX.D1.pas',
  LUX.D2 in '_LIBRARY\LUXOPHIA\LUX\LUX.D2.pas',
  LUX.D2x2 in '_LIBRARY\LUXOPHIA\LUX\LUX.D2x2.pas',
  LUX.D3 in '_LIBRARY\LUXOPHIA\LUX\LUX.D3.pas',
  LUX.D3x3 in '_LIBRARY\LUXOPHIA\LUX\LUX.D3x3.pas',
  LUX.D4 in '_LIBRARY\LUXOPHIA\LUX\LUX.D4.pas',
  LUX.D4x4 in '_LIBRARY\LUXOPHIA\LUX\LUX.D4x4.pas',
  LUX.Quaternion in '_LIBRARY\LUXOPHIA\LUX\Quaternion\LUX.Quaternion.pas',
  LUX.Data.Grid.D1 in '_LIBRARY\LUXOPHIA\LUX\Data\Grid\LUX.Data.Grid.D1.pas',
  LUX.Curve in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.pas',
  LUX.Curve.Linear in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.Linear.pas',
  LUX.Curve.Bezier in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.Bezier.pas',
  LUX.Curve.BSpline in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.BSpline.pas',
  LUX.Curve.CatmullRom in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.CatmullRom.pas',
  LUX.Curve.Lanczos in '_LIBRARY\LUXOPHIA\LUX\Curve\LUX.Curve.Lanczos.pas',
  LUX.Curve.Data.Grid.D1 in '_LIBRARY\LUXOPHIA\LUX\Curve\Data\Grid\LUX.Curve.Data.Grid.D1.pas',
  LUX.Curve.Data.Grid.D1.Plots in '_LIBRARY\LUXOPHIA\LUX\Curve\Data\Grid\LUX.Curve.Data.Grid.D1.Plots.pas',
  LUX.FMX.Graphics.D3 in '_LIBRARY\LUXOPHIA\LUX.FMX.Graphics.D3\LUX.FMX.Graphics.D3.pas',
  LUX.FMX.Graphics.D3.Shaper in '_LIBRARY\LUXOPHIA\LUX.FMX.Graphics.D3\LUX.FMX.Graphics.D3.Shaper.pas',
  LUX.S2 in '_LIBRARY\LUXOPHIA\LUX.Sphere\S2\LUX.S2.pas',
  LUX.S2.Data.Grid.D1 in '_LIBRARY\LUXOPHIA\LUX.Sphere\S2\Data\Grid\LUX.S2.Data.Grid.D1.pas',
  LUX.S3 in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\LUX.S3.pas',
  LUX.S3.Data.Grid.D1 in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Data\Grid\LUX.S3.Data.Grid.D1.pas',
  LUX.S3.Data.Grid.D1.Plots in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Data\Grid\LUX.S3.Data.Grid.D1.Plots.pas',
  LUX.S3.Curve in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.pas',
  LUX.S3.Curve.Glerp in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.Glerp.pas',
  LUX.S3.Curve.Slerp in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.Slerp.pas',
  LUX.S3.Curve.PowSlerp in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.PowSlerp.pas',
  LUX.S3.Curve.PolySlerp in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.PolySlerp.pas',
  LUX.S3.Curve.ExpMap in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.ExpMap.pas',
  LUX.S3.Curve.ModExpMap in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\Curve\LUX.S3.Curve.ModExpMap.pas',
  LUX.S3.FMX in '_LIBRARY\LUXOPHIA\LUX.Sphere\S3\FMX\LUX.S3.FMX.pas',
  LIB.Bary in '_LIBRARY\Bary\LIB.Bary.pas',
  LIB.Bary.S3 in '_LIBRARY\Bary\S3\LIB.Bary.S3.pas',
  LIB.Bary.S3.Glerp in '_LIBRARY\Bary\S3\LIB.Bary.S3.Glerp.pas',
  LIB.Bary.S3.Slerp in '_LIBRARY\Bary\S3\LIB.Bary.S3.Slerp.pas',
  LIB.Bary.S3.PowSlerp in '_LIBRARY\Bary\S3\LIB.Bary.S3.PowSlerp.pas',
  LIB.Bary.S3.PolySlerp in '_LIBRARY\Bary\S3\LIB.Bary.S3.PolySlerp.pas',
  LIB.Bary.S3.ExpMap in '_LIBRARY\Bary\S3\LIB.Bary.S3.ExpMap.pas',
  LIB.Bary.S3.ModExpMap in '_LIBRARY\Bary\S3\LIB.Bary.S3.ModExpMap.pas',
  LIB.Curve in '_LIBRARY\Curve\LIB.Curve.pas',
  LIB.Curve.Linear in '_LIBRARY\Curve\LIB.Curve.Linear.pas',
  LIB.Curve.Bezier in '_LIBRARY\Curve\LIB.Curve.Bezier.pas',
  LIB.Curve.BSpline in '_LIBRARY\Curve\LIB.Curve.BSpline.pas',
  LIB.Curve.CatmullRom in '_LIBRARY\Curve\LIB.Curve.CatmullRom.pas',
  LIB.Curve.Lanczos in '_LIBRARY\Curve\LIB.Curve.Lanczos.pas',
  LIB.Curve.S3 in '_LIBRARY\Curve\S3\LIB.Curve.S3.pas',
  LIB.Curve.S3.Linear in '_LIBRARY\Curve\S3\LIB.Curve.S3.Linear.pas',
  LIB.Curve.S3.Bezier in '_LIBRARY\Curve\S3\LIB.Curve.S3.Bezier.pas',
  LIB.Curve.S3.BSpline in '_LIBRARY\Curve\S3\LIB.Curve.S3.BSpline.pas',
  LIB.Curve.S3.CatmullRom in '_LIBRARY\Curve\S3\LIB.Curve.S3.CatmullRom.pas',
  LIB.Curve.S3.Lanczos in '_LIBRARY\Curve\S3\LIB.Curve.S3.Lanczos.pas',
  Main in 'Main.pas' {Form1},
  Scene in 'Scene.pas',
  LUX.Sphere.FMX in '_LIBRARY\LUXOPHIA\LUX.Sphere\FMX\LUX.Sphere.FMX.pas',
  LUX.Curve.D3.Linear in '_LIBRARY\LUXOPHIA\LUX\Curve\D3\LUX.Curve.D3.Linear.pas',
  LUX.Curve.Q4.Linear in '_LIBRARY\LUXOPHIA\LUX\Curve\Q4\LUX.Curve.Q4.Linear.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
